# Generated by Django 5.1 on 2024-09-12 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='semester',
            old_name='semester',
            new_name='semester_name',
        ),
        migrations.AlterField(
            model_name='aggregateresult',
            name='cgpa',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='aggregateresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aggregate_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='semester',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Result',
        ),
    ]
