# Generated by Django 5.1 on 2024-09-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_semester_semester_semester_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='sgpa',
            field=models.FloatField(default=0.0),
        ),
    ]
