# Generated by Django 5.1 on 2024-09-12 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_semester_sgpa'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('user', 'semester_name')},
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('name', 'credit')},
        ),
        migrations.RemoveField(
            model_name='semester',
            name='subjects',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='updated_at',
        ),
        migrations.CreateModel(
            name='UserSubjectGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=2)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'subject', 'semester')},
            },
        ),
    ]
